### ISSUE TITLE
add multiple obs

### ISSUE THREAD

**Issue by goliveok** [zijiren233/livelib#2]
hi

Is it possible add more than one obs and give each one a name to call them by their name
i need multiple clients output and multiple input from name or id
example 
----------------
rtmp://127.0.0.1:1935/app/channel1
rtmp://127.0.0.1:1935/app/channel2
rtmp://127.0.0.1:1935/app/channel3
rtmp://127.0.0.1:1935/app/channel4
rtmp://127.0.0.1:1935/app/channel5
+
+
+
+

thnks

**Comment by zijiren233** [comment]
Of course you can use multiple obs to push streams to multiple addresses and pull video streams through multiple URLs.
like:
rtmp://127.0.0.1:1935/app1/ch1 rtmp://127.0.0.1:1935/app2/ch1 rtmp://127.0.0.1:1935/app2/ch2
Pull:
http://127.0.0.1:1935/app1/ch1.flv
...

**Comment by goliveok** [comment]
thank you for helping me 

Is it possible modify problem crash hls m3u8 and add output from utl http://127.0.0.1:1935/live/ch1.ts

ffplay http://127.0.0.1:1935/app/2..m3u8
Failed to open segment 447 of playlist 0/0   
[http @ 0x7fa920564f80] Opening 'http://127.0.0.1:1935/app/2..m3u8' for reading
[hls @ 0x7fa920000cc0] Skip ('#EXT-X-VERSION:3')B sq=    0B f=0/0   
[hls @ 0x7fa920000cc0] Skip ('#EXT-X-ALLOW-CACHE:NO')
[http @ 0x7fa9204c6c80] Opening 'http://127.0.0.1:1935/app/2./1700845766982990.ts' for reading
[hls @ 0x7fa920000cc0] Opening 'http://127.0.0.1:1935/app/2./1700845770966107.ts' for reading
[mpegts @ 0x7fa920007940] PES packet size mismatchsq=    0B f=0/0   
[mpegts @ 0x7fa920007940] Packet corrupt (stream = 0, dts = 160362000).
[h264 @ 0x7fa920195580] cabac decode of qscale diff failed at 2 14
[h264 @ 0x7fa920195580] error while decoding MB 2 14, bytestream 534
