### ISSUE TITLE
crash hls m3u8

### ISSUE THREAD

**Issue by goliveok** [zijiren233/livelib#3]
thank you for helping me

Is it possible modify problem crash hls m3u8 and add output from utl http://127.0.0.1:1935/app/ch1.ts

ffplay http://127.0.0.1:1935/app/ch1..m3u8
Failed to open segment 447 of playlist 0/0
[http @ 0x7fa920564f80] Opening 'http://127.0.0.1:1935/app/ch1..m3u8' for reading
[hls @ 0x7fa920000cc0] Skip ('#EXT-X-VERSION:3')B sq= 0B f=0/0
[hls @ 0x7fa920000cc0] Skip ('#EXT-X-ALLOW-CACHE:NO')
[http @ 0x7fa9204c6c80] Opening 'http://127.0.0.1:1935/app/ch1./1700845766982990.ts' for reading
[hls @ 0x7fa920000cc0] Opening 'http://127.0.0.1:1935/app/ch1./1700845770966107.ts' for reading
[mpegts @ 0x7fa920007940] PES packet size mismatchsq= 0B f=0/0
[mpegts @ 0x7fa920007940] Packet corrupt (stream = 0, dts = 160362000).
[h264 @ 0x7fa920195580] cabac decode of qscale diff failed at 2 14
[h264 @ 0x7fa920195580] error while decoding MB 2 14, bytestream 534

and in vlc problem crash hls m3u8

**Comment by zijiren233** [comment]
not `http://127.0.0.1:1935/app/ch1..m3u8`

instead `http://127.0.0.1:1935/app/ch1.m3u8`
